### ISSUE TITLE
Database is locked in Kubernetes run container

### ISSUE THREAD

**Issue by psychemedia** [ouseful-testing/nbsearch#21]
For some reason, getting an `OperationalError: database is locked` when running in a container launched via JupyterHub/Kubernetes.

Could this be the issue? https://github.com/kubernetes/kubernetes/issues/61767

**Comment by psychemedia** [comment]
@mmh352 fixed things in the TM129 JupyterHub Azure k8s server. Not sure what the exact fix was but it was maybe just a simple mountOption (though from what to what I don't know).

**Comment by mmh352** [comment]
The fix was setting the network drive mount parameters correctly, which let sqlite then write to the database.

**Comment by psychemedia** [comment]
@mmh352 Yep. So are you happy to share those parameters here, or clarify whether and which part any of the linked to issues provided the solution? Or is it one of those "every system is different and you just have to figure out what works for yourself" situations?

**Comment by mmh352** [comment]
Sure. The solution obviously only applies to running JupyterHub on k8s on Azure. You create a Azurefile storageclass https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv and in the options for that you set the "nobrl" parameter.
